### ISSUE TITLE
Error on const, shader validation on older shader language version ?

### ISSUE THREAD

**Issue by cedricpinson** [PolyMeilex/vscode-wgsl#14]
Hi,
first of all, this extension is great. GG

I tried to use in vscode but it seems that the validation produces errors when chrome canary is fine with the shader. It seems like the validation is not up to date with the shading language.
on this one the first line produces an error.

--> webgpu-experiment/src/node-functions.wgsl:2:1
error: error: expected global item ('struct', 'let', 'var', 'type', ';', 'fn') or the end of the file, found 'const'
  ┌─ wgsl:2:1
  │
2 │ const NodeMaxLevel = 14;
  │ ^^^^^ expected global item ('struct', 'let', 'var', 'type', ';', 'fn') or the end of the file

Note that this shader is injected a bit like include in a more complex compute shader and vertex shader. Still It feels that it validates on a different version and the language.

[node-functions.txt](https://github.com/PolyMeilex/vscode-wgsl/files/10070167/node-functions.txt)

**Comment by PolyMeilex** [comment]
const are not yet supported in `naga`: https://github.com/gfx-rs/naga/issues/2071 should be fixed in https://github.com/gfx-rs/naga/pull/2075

That being said, naga was indeed outdated, so I updated it, and published `cargo-wgsl 0.0.12`

**Comment by cedricpinson** [comment]
🙏 thx

**Comment by PolyMeilex** [comment]
I'd like to keep that open, if you don't mind. Just to keep track of that.

**Comment by cedricpinson** [comment]
Ho np 👍

**Comment by codeart1st** [comment]
New versions are released with const support.

**Comment by PolyMeilex** [comment]
> New versions are released with const support.

Great will take a look at that, thanks.

**Comment by PolyMeilex** [comment]
Indeed it is now working as expected. cargo-wgsl is also updated already so vscode-wgsl just works :tm:
