### ISSUE TITLE
Support Predeclared aliases

### ISSUE THREAD

**Issue by Snapstromegon** [PolyMeilex/vscode-wgsl#23]
The WGSL standard declares some [aliases](https://www.w3.org/TR/WGSL/#vector-types) for some vector types.

Among these are:
```wgsl
alias vec2i = vec2<i32>
alias vec3i = vec3<i32>
alias vec4i = vec4<i32>
alias vec2u = vec2<u32>
alias vec3u = vec3<u32>
alias vec4u = vec4<u32>
alias vec2f = vec2<f32>
alias vec3f = vec3<f32>
alias vec4f = vec4<f32>
alias vec2h = vec2<f16>
alias vec3h = vec3<f16>
alias vec4h = vec4<f16>
```

Sadly the extension currently doesn't recognize these as built-in types. Since they are used in some popular tutorials and are part of the standard, it would probably be good to include them.

If this is not the right repo to add these, please tell me where to look.

**Comment by PolyMeilex** [comment]
Oh yeah, thanks for the issue, I missed that those were added at some point
Here is PR for that #24, would appreciate if you could check if it includes all the types you'd expect.
