### ISSUE TITLE
Can't install in VS Codium

### ISSUE THREAD

**Issue by john01dav** [PolyMeilex/vscode-wgsl#3]
I tried to install this extension in [VS Codium](https://vscodium.com/) (FOSS fork of vs code without the telemetry), but it is not showing up:
![screenshot of "No extensions found." showing up in vscode when searching for this extension](https://user-images.githubusercontent.com/3982497/124273249-632ac980-db05-11eb-8a2c-e6bc0e96839b.png)

Most other extensions show up just fine, but not all as some insist on a proprietary VS Code build. It would appear that this plugin is in that category (although it might be something else; I don't know enough about VS Code to know for sure), although that seems unusual for this sort of plugin, so perhaps it is an error?

**Comment by PolyMeilex** [comment]
>  as some insist on a proprietary VS Code build.

I don't insist on proprietary in any way.

As far as I know, I would have to publish the extension twice, once in VS Code registry and once in https://open-vsx.org/ registry, that's quite annoying to be honest, but maybe I'll find a way to automate this ([publish-vscode-extension](https://github.com/HaaLeo/publish-vscode-extension) looks promising)

**Comment by PolyMeilex** [comment]
Here you go: https://open-vsx.org/extension/PolyMeilex/wgsl
Let me know if it shows up correctly in VS Codium

**Comment by PolyMeilex** [comment]
I assume that it does work, so I'm closing this
