### ISSUE TITLE
Doesn't handle block comments?

### ISSUE THREAD

**Issue by greggman** [PolyMeilex/vscode-wgsl#7]
<img width="223" alt="Screen Shot 2021-12-23 at 4 23 21 PM" src="https://user-images.githubusercontent.com/234804/147301594-0991f47d-8d27-4b4f-9872-c57090f29bbf.png">

**Comment by PolyMeilex** [comment]
Sorry for the absurdly long delay, fixed and published as part of `0.1.14`
